### ISSUE TITLE
Issue with modify_cluster_instance_size

### ISSUE THREAD

**Issue by shaunster666** [mgmonteleone/python-atlasapi#29]
Hi,

Please could you tell me what I am doing wrong here?

When I run this script I get this error:

"Object of type ProviderSettings is not JSON serializable"

Sorry for trivial question

Many thanks

```
#!/usr/local/bin/python3

from atlasapi.atlas import Atlas
from atlasapi.clusters import  AdvancedOptions

a = Atlas("uuuuuuu","yyyyyyyyyyyyy","xxxxxx")

a.Clusters.modify_cluster_instance_size(cluster='Cluster0',new_cluster_size='InstanceSizeName.M20')


```

**Comment by mgmonteleone** [comment]
Sorry for the huge delay in answering!

I believe the issue here is that your are sending the `new_cluster_size` as `str`, not `InstanceSizeName`

Could you try like this:

```
from atlasapi.atlas import Atlas
from atlasapi.clusters import  AdvancedOptions, InstanceSizeName


a = Atlas(user="xxxxxx",password="xxxxxxxx",group="xxxxxxx")

out =a.Clusters.modify_cluster_instance_size(cluster='Cluster0',new_cluster_size=InstanceSizeName.M10)

print(out)
```

I am going to add a type check here as well to make that easier to find.

Please let me know if that does not resolve the issue, and if it doesn't, can you please send the error?

**Comment by mgmonteleone** [comment]
I have not been able to reproduce this issue, and think that the procedure above will work, so closing this for now. Please re-open if you are still having issues.
